#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

ROOT_DIR="$ROOT_DIR" node <<'NODE'
const fs = require("node:fs");
const path = require("node:path");

const rootDir = process.env.ROOT_DIR;
const resourcesDir = path.join(rootDir, "resources");
const packageJson = JSON.parse(fs.readFileSync(path.join(rootDir, "package.json"), "utf8"));
const projectName = packageJson.name || path.basename(rootDir);

const escapeText = (value) =>
  value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

const mimeTypes = {
  ".jpg": "image/jpeg",
  ".png": "image/png",
};

const heroPresetPath = path.join(resourcesDir, "readme-hero.preset.svg");
const heroOutputPath = path.join(resourcesDir, "readme-hero.svg");
let heroSvg = fs.readFileSync(heroPresetPath, "utf8");

heroSvg = heroSvg.replace(">readme-md</text>", `>${escapeText(projectName)}</text>`);
heroSvg = heroSvg.replace(/<image\b[^>]*href="\.\/([^"]+)"[^>]*\/>/g, (tag, fileName) => {
  const imagePath = path.join(resourcesDir, fileName);

  if (!fs.existsSync(imagePath)) {
    return "";
  }

  const extension = path.extname(fileName).toLowerCase();
  const mimeType = mimeTypes[extension];

  if (!mimeType) {
    return "";
  }

  const data = fs.readFileSync(imagePath).toString("base64");
  return tag.replace(`href="./${fileName}"`, `href="data:${mimeType};base64,${data}"`);
});

fs.writeFileSync(heroOutputPath, `${heroSvg.trim()}\n`);

const readmePresetPath = path.join(resourcesDir, "README.preset.md");
const readmeOutputPath = path.join(rootDir, "README.md");
const readmePreset = fs.readFileSync(readmePresetPath, "utf8").trimEnd();
const generatedHeader = `<!--
  This file is automatically generated based on resources/README.preset.md.
  Any direct modifications to this file will be lost.
  If changes are needed, please modify the resources/README.preset.md file.
  Then run ./scripts/readme_update.sh.
-->
`;

fs.writeFileSync(readmeOutputPath, `${generatedHeader}\n${readmePreset}\n`);
NODE
